title: CorSys
logo: ./logo.png
description: Generating and comparing low-rate deletion correcting codes.
show_downloads: true
google_analytics:
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
- jekyll-remote-theme
