#
#   @file : dependency-review.yml
#   @date : 13 April 2024
#   @authors : Orel Adivi and Daniel Noor
#
# Dependency Review
name: Dependency Review - Security

on: [pull_request]

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v3
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v2
