#
#   @file : latex.yml
#   @date : 05 May 2024
#   @authors : Orel Adivi and Daniel Noor
#
name: Generate LaTex file - Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PDF

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Convert LaTeX to pdf
      id: convert-to-pdf
      uses: closoco/pdflatex-action@v1.0.0
      with:
        texFile: ./report/report.tex
    - name: Store pdf
      uses: actions/upload-artifact@v2
      with:
        name: report.pdf
        path: report.pdf
    - name: Store pdf1
      uses: actions/upload-artifact@v2
      with:
        name: ./report/report.pdf
        path: report/report.pdf
