#
#   @file : latex.yml
#   @date : 05 May 2024
#   @authors : Orel Adivi and Daniel Noor
#
name: Generate LaTex file - Report

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build PDF

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Remove current report
      run: rm ./report.pdf

    - name: Convert LaTeX to pdf
      uses: xu-cheng/latex-action@3.2.0
      with:
        root_file: report.tex

    - name: Store artifact
      uses: actions/upload-artifact@v4
      with:
        name: Report PDF file
        path: report.pdf
